sudo: false

language: php

matrix:
    fast_finish: true
    include:
        - php: 5.5
        - php: 5.6
        - php: 7
        - php: hhvm
    allow_failures:
        - php: 7
        - php: hhvm

before_install:
    - composer self-update

install:
    - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source --no-scripts

script:
    - mkdir -p build/logs
    - phpunit --coverage-text --coverage-clover=build/logs/clover.xml --colors

after_script:
    - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi

notifications:
    email: true
